### ISSUE TITLE
How to get the parameters of airfoil？

### ISSUE THREAD

**Issue by ZhangYang9992** [peterdsharpe/NeuralFoil#1]
Dear @peterdsharpe,
Hii, I have a question that how can I get the parameters of airfoil, like chrod length, maximum thickness and its position, mean camber line, maximum camver and its position, leading edge radius and trailing edge angle (provided by Xfoil).  Looking forward to you reply. Thank you :)

**Comment by peterdsharpe** [comment]
Hi - what is your current airfoil representation? Do you have it as an ndarray of coordinates, a `*.dat` file, an AeroSandbox `Airfoil` object, a series of CST parameters, etc.?

**Comment by ZhangYang9992** [comment]
The current airfoil representation is an ndarray of coordinates.

**Comment by peterdsharpe** [comment]
For that, I would use [AeroSandbox](https://github.com/peterdsharpe/AeroSandbox):

```python
import aerosandbox as asb

af = asb.Airfoil(name="My Airfoil", coordinates=my_coordinates_array)

af.max_thickness()
af.max_camber()

x_over_c_sample = np.linspace(0, 1, 1000)
mean_camber_line = af.local_camber(x_over_c_sample)
max_camber_loc = x_over_c_sample[np.argmax(mean_camber_line)]

af.TE_angle()
```
and so on.

**Comment by ZhangYang9992** [comment]
Very thanks for your reply, it's very useful for me. However, when I try to calculate the max thickness of the airfoil, I have a question (the max thickness is zero, and  I printed local_thickness() and found that were all negative). The source code ues function LE_index to calculate lower surface coordinates and upper surface coordinates, it looks like calculate the index of the smallest element in the array. But my airfoil representation is an ndarray of coordinates, the upper and lower surfaces are distinguished by the median of the y coordinates. Is there a problem with my coordinates?  I'm sorry that I don't know much about Airfoil, I don't know if it's my problem. Thank you very much for your answer!!! :)
```
def LE_index(self) -> int:
    """
    Returns the index of the leading edge point in the airfoil coordinates.
    """
    return int(np.argmin(self.x()))
```

**Comment by peterdsharpe** [comment]
This is a non-standard airfoil coordinate format; read up on Selig format (or look at *.dat files from the UIUC database). Closing issue as this is off-topic to NeuralFoil.
